#!/bin/bash

board="${1:-x86_64}"

monitor() {
	build_dir="output/$board/build"
	build_list=($(make "${board}-show-build-order" | grep -v " " | grep -v \#))
	tail -f "${build_dir}/build-time.log" | while read -r line; do
		progress_list=( "${build_dir}"/*/.stamp_installed )
		line=$(sed -E 's/[0-9]+\.[0-9]+\://' <<< "$line")         # strip unwanted timestamp
	    [[ $line =~ end\ +\:install ]] && eol="\n" || eol="\r"  # only linefeed when task is done
		printf 'Package Count: %d / %d : %s : %s'"$eol" \
			"${#progress_list[@]}" \
			"${#build_list[@]}" \
			"$(date -Iseconds)" \
			"$line"
	done
}

monitor "$board"
